baseURL: https://andrijasinski.eu
title: Snaps by Andri
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: ''
enableRobotsTXT: true
timeout: 1m

params:
  logo: logo.png
  subtitle: "Photography journey of Andri Jasinski"
  copyright: All rights reserved.
  author: Andri Jasinski
  dontShowSource: true
  dontShowLogo: true
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 1
  socials:
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.com/andrijasinski'
      landing: true
    # - icon: 'fa-solid fa-camera-retro fa-lg'
    #   url: 'https://www.lomography.com/homes/andrijasinski/'
    #   landing: true
    # - icon: 'fab fa-github fa-lg'
    #   url: 'https://github.com/andrijasinski'
    #   landing: true
    # - icon: 'fab fa-linkedin-in fa-lg'
    #   url: 'https://www.linkedin.com/in/andri-jasinski/'
    #   landing: true
  homepage: "/portfolio" # homepage link, mostly same with menu.main[0]
  specialPages:
    - portfolio
    - archive
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: true # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  portfolio: ":filename/"

menu:
  main:
    - name: portfolio
      url: /portfolio/
      weight: 1
    - name: andalucia
      url: /tags/andalucia/
      weight: 2
    - name: everything-everywhere
      url: /tags/archive/
      weight: 6
    - name: albums
      url: /tags/
      weight: 7
    - name: about
      url: /about/
      weight: 8
